language: go
go:
 - 1.6
 - 1.7
 - 1.8
# - tip

addons:
  postgresql: "9.4"

services:
  - postgresql

before_install:
  - go get -t github.com/npiganeau/yep
  - yep generate -t ./yep/tests/test_module

before_script:
  - psql -c 'create database yep_test_models;' -U postgres
  - psql -c 'create database yep_test_tests;' -U postgres

env:
  - YEP_DB_DRIVER=postgres YEP_DB_USER=postgres YEP_DB_PASSWORD= YEP_DB_PREFIX=yep_test
