language: go
go:
 - 1.6
 - 1.7
 - tip

addons:
  postgresql: "9.4"

services:
  - postgresql

before_install:
  - go get -t github.com/npiganeau/yep/cmd/yep-generate
  - go install github.com/npiganeau/yep/cmd/yep-generate
  - yep-generate

before_script:
  - psql -c 'create database yep_test_models;' -U postgres
  - psql -c 'create database yep_test_tests;' -U postgres

env:
- YEP_DB_DRIVER=postgres YEP_DB_USER=postgres YEP_DB_PASSWORD= YEP_DEBUG=1 YEP_DB_PREFIX=yep_test
