language: go
go:
 - 1.6
 - 1.7
 - 1.8
 - tip

addons:
  postgresql: "9.4"

services:
  - postgresql

before_install:
  - go get -t github.com/hexya-erp/hexya
  - hexya generate -t ./hexya/tests/testmodule

before_script:
  - psql -c 'create database hexya_test_models;' -U postgres
  - psql -c 'create database hexya_test_tests;' -U postgres

env:
  - HEXYA_DB_DRIVER=postgres HEXYA_DB_USER=postgres HEXYA_DB_PASSWORD= HEXYA_DB_PREFIX=hexya_test
