language: go
go:
 - 1.5.1
 - release
 - tip

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql
  - sqlite3

before_script:
  - psql -c 'create database yep_test;' -U postgres
  - mysql -e 'create database yep_test;'

env:
- ORM_DRIVER=postgres ORM_SOURCE="dbname=yep_test sslmode=disable user=postgres"
- ORM_DRIVER=mysql ORM_SOURCE="root:@/yep_test?charset=utf8"
- ORM_DRIVER=sqlite3 ORM_SOURCE='file:yep_test?mode=memory'
